Console.Write("Введите первое число:");
int num1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите второе число:");
int num2 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите третье число:");
int num3 = Convert.ToInt32(Console.ReadLine());
int maxnumber = num1;
   if (num2>maxnumber) maxnumber = num2;
   if (num3>maxnumber) maxnumber = num3;
Console.WriteLine($"Наибольшее из трех чисел = {maxnumber}");